language: emacs-elisp
root: false
before_install:
  - curl -fsSkL https://gist.github.com/rejeep/ebcd57c3af83b049833b/raw > x.sh && source ./x.sh
  - evm install $EVM_EMACS --use --skip
  - cask install
  
env:
  global:
    - CURL="curl -fsSkL --retry 9 --retry-delay 9"
  matrix:
    - EMACS_VERSION=25.3
    - EMACS_VERSION=26.1
    - EMACS_VERSION=27.1
    - EMACS_VERSION=master
    
script:
  - emacs --version
  - cask build
  - cask clean-elc
  - cask exec ert-runner -l test/ert-helper.el test/*-tests.el
  - cask emacs --batch -Q -l package-lint.el -f package-lint-batch-and-exit lisp/*.el
  
notifications:
    webhooks:
        urls:
          - "https://scalar.vector.im/api/neb/services/hooks/dHJhdmlzLWNpLyU0MGpvaG5zb24lM0FtYXRyaXgub3JnLyUyMVpSbGVnVEFCTHBTQmJ2c01tTiUzQW1hdHJpeC5vcmc"
        on_success: always # always|never|change
        on_failure: always
        on_start: never
